# Generated by Django 5.2.4 on 2025-07-04 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customr_name', models.CharField(max_length=30)),
                ('owner_name', models.CharField(max_length=30)),
                ('price_per_meter', models.IntegerField(default=0)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
