# Generated by Django 5.2.4 on 2025-07-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('contact_person_name', models.CharField(max_length=150)),
                ('designation', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=200)),
                ('contact_no', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('product', models.CharField(verbose_name=200)),
            ],
        ),
    ]
