# Generated by Django 5.2.4 on 2025-07-08 15:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ink_type', models.CharField(choices=[('sublimation', 'Sublimation Ink'), ('dtf', 'DTF Ink')], max_length=20)),
                ('ink_description', models.CharField(max_length=200)),
                ('bottle_type', models.CharField(choices=[('0.5', '500ml'), ('1', '1L'), ('2', '2L'), ('5', '5L'), ('10', '10L')], max_length=5)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('unit', models.CharField(choices=[('l', 'Liters')], max_length=20)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
