# Generated by Django 5.2.4 on 2025-07-08 16:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ink'),
    ]

    operations = [
        migrations.CreateModel(
            name='SublimationPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_size', models.CharField(max_length=50)),
                ('paper_description', models.CharField(max_length=200)),
                ('gsm', models.PositiveIntegerField(help_text='Grams per square meter')),
                ('qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit', models.CharField(max_length=20)),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
