# Generated by Django 5.2.4 on 2025-07-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sublimationpaper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='product',
            field=models.CharField(max_length=200),
        ),
    ]
