# Generated by Django 5.2.4 on 2025-07-11 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_supplier_address_alter_supplier_contact_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sublimationpaper',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.supplier'),
        ),
    ]
