# Generated by Django 5.2.4 on 2025-07-13 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_purchaseink_delete_ink'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SublimationPaper',
            new_name='PurchaseSublimationPaper',
        ),
    ]
