# Generated by Django 5.2.4 on 2025-07-15 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_sublimationpaper_purchasesublimationpaper'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('unit_price', models.IntegerField()),
                ('total_amount', models.IntegerField()),
                ('produced', models.IntegerField(default=0)),
                ('delivered', models.IntegerField(default=0)),
                ('remarks', models.CharField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer')),
            ],
        ),
    ]
