# Generated by Django 5.2.4 on 2025-07-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_paid_amount',
            field=models.IntegerField(default=0),
        ),
    ]
