# Generated by Django 5.2.4 on 2025-08-01 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_journal_description'),
        ('core', '0012_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customr_name',
            new_name='customer_name',
        ),
        migrations.AddField(
            model_name='payment',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.accounting_account'),
        ),
    ]
