# Generated by Django 5.2.4 on 2025-07-26 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='ref',
            field=models.CharField(blank=True, null=True),
        ),
    ]
