# Generated by Django 5.2.4 on 2025-08-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_journal_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
