# Generated by Django 5.2.4 on 2025-08-03 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_journal_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounting_account',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='accounting.category'),
        ),
    ]
