# Generated by Django 5.2.4 on 2025-08-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_accounting_account_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounting_account',
            name='sort',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
