# Generated by Django 5.2.4 on 2025-08-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_accounting_account_sort'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sort',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
