# Generated by Django 5.2.4 on 2025-08-04 14:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_category_sort'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
